### ISSUE TITLE
feature request: make cligen unicode safe

### ISSUE THREAD

**Issue by dcornejo** [olofhagsand/cligen#21]
please make cligen capable of handling unicode

**Comment by olofhagsand** [comment]
Thanks for pointing this out. CLIgen should now be UTF8 "safe".
I added an experimental UTF8 mode as well, but it does not work w control editing, scrolling, etc:
cligen> öåß®.

**Comment by rohitrajskk** [comment]
Hello @olofhagsand 

Is multi-byte Unicode supported?

I am unable to type a string in the CLI prompt with multibyte Unicode.
Example string:
Chassis temperature is {{$value}}°C
If you see below, ° is not getting pasted in the CLI prompt.
supervisor@udp>rohit: cfg> set time-series alert chassis_temperature_alarm summary "Chassis temperature is {{$value}}C"

**Comment by olofhagsand** [comment]
No, the CLI does not support unicode. 
This ticket just made it "safe", essentially ignoring it.
There is experimental code enabled by cligen_utf8_set(h, 1) but it only partly works.

**Comment by olofhagsand** [comment]
More precisely, it works in commands, comments and help-texts, but not in variable input.
The experimental code is for making it work in variable input.
With variable input I mean eg <var:string> where the user types input to var.
The problem is that getline in cligen uses C string functions which do not support unicode.
It is possible to do but has not been prioritized.

**Comment by rohitrajskk** [comment]
Thanks for the quick response.

I misunderstood this commit as support for Unicode.

**Comment by olofhagsand** [comment]
I agree it is unclear.
Maybe you could add a more specific feature request?
