### ISSUE TITLE
Multiple Callbacks Executed When Terminal Command Has Children

### ISSUE THREAD

**Issue by owenlejeune** [olofhagsand/cligen#39]
I currently have this tree structure in my .cli file:
```
aa {
    bb, cb(); {
        (
            [cc]
            [dd]
        ), cb();
    }
}
```
When I execute the command `aa bb`, the callback `cb()` is execute twice, however it is only executed once for the commands `aa bb cc`, `aa bb dd`, etc.  Is this expected behaviour?

**Comment by olofhagsand** [comment]
If you use -p for cligen_file for example, you can see which underlying cligen tree that the input is mapped to, eg in the case above:
```
./cligen_file -p -f f
aa bb, cb(), cb();{
      cc, cb();{
         dd, cb();
      }
      dd, cb();
   }
```
It may not be completely obvious but one result of aa bb [cc] [dd] is aa bb. Which means aa bb has two instances above. Workaround: remove the first cb(), since it is covered by the second. Alternatively, instead of [cc][dd], do (cc|dd)

**Comment by owenlejeune** [comment]
Okay thank you!  I will remove the duplicate callbacks from my .cli file then.
